version: '3'

services:
  app:
    build: '.'
    depends_on:
      - "db"
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sample_app
  influx:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - $PWD/influxdb:/var/lib/influxdb
  grafana:
    depends_on:
      - influx
    image: grafana/grafana:latest
    volumes:
      - $PWD/grafana:/var/lib/grafana
    ports:
      - 3000:3000
  jmeter:
    image: justb4/jmeter:3.3
    labels:
      role: "jmeter"
    volumes:
      - ./jmeter:/tests
    entrypoint: tail -f /dev/null
